#default: &default
#  adapter: postgresql
#  encoding: unicode
#  host: db
#  username: postgres
#  password:
#  pool: 5

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test